---
  # this is not an installation script. It assumes the db, as well as public dir & service already exists and running
- name: Deploy web-site
  hosts: aghost
  remote_user: tabula
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python
  vars_prompt:
    - name: commit
      prompt: "What is the commit name?"
      private: no

  tasks:
    - name: build assets & binary for production
      delegate_to: localhost
      shell: make build

    - name: git push
      delegate_to: localhost
      shell: git add -A && git commit -m "{{ commit }}" ; git push origin master

    # - name: Copy config directory
    #   copy:
    #     src: "{{ playbook_dir }}/config/"
    #     dest: /home/tabula/medical/config/
      
    - name: Copy css directory
      copy:
        src: "{{ playbook_dir }}/public/css/"
        dest: /home/tabula/medical/public/css/
        force: yes
        owner: tabula
        group: tabula

    - name: Copy js directory
      copy:
        src: "{{ playbook_dir }}/public/js/"
        dest: /home/tabula/medical/public/js/

    # - name: Copy views directory
    #   copy:
    #     src: "{{ playbook_dir }}/views/"
    #     dest: /home/tabula/medical/views/

    - name: Copy binary
      copy:
        src: "{{ playbook_dir }}/miobalans-go"
        dest: /home/tabula/medical
        mode: 0755
    
    - name: restart service
      shell: systemctl restart medical
      become: yes
